
export async function getAllEvents() {
    return [
      {
        id: '1',
        title: 'Nashville Tech Expo 2025',
        time: '10:00 AM - 6:00 PM',
        location: 'Music City Center, Nashville, TN',
        category: 'Technology',
        image: '/images/movie-park.jpg',
        description: 'Explore the latest advancements in technology, network with industry leaders, and discover innovative startups.',
      },
      {
        id: '2',
        title: 'Music City Food & Wine Festival',
        time: '12:00 PM - 10:00 PM',
        location: 'Riverfront Park, Nashville, TN',
        category: 'Food & Drink',
        image: '/images/movie-park.jpg',
        description: 'A culinary celebration featuring renowned chefs, exquisite wines, and delicious food from Nashville\'s top restaurants.',
      },
      {
        id: '3',
        title: 'Nashville Film Festival',
        time: 'Various Screenings',
        location: 'Belcourt Theatre, Nashville, TN',
        category: 'Film',
        image: '/images/movie-park.jpg',
        description: 'Experience a diverse selection of independent films, documentaries, and short features from around the world.',
      },
      {
        id: '4',
        title: 'CMA Music Festival',
        time: 'All Day Events',
        location: 'Downtown Nashville, TN',
        category: 'Music',
        image: '/images/movie-park.jpg',
        description: 'The ultimate country music fan experience with concerts, meet-and-greets, and performances by the biggest stars.',
      },
      {
        id: '5',
        title: 'Nashville Pride Festival',
        time: 'Various Events',
        location: 'Public Square Park, Nashville, TN',
        category: 'Community',
        image: '/images/movie-park.jpg',
        description: 'A vibrant celebration of the LGBTQ+ community, promoting inclusivity, equality, and pride through music, parades, and events.',
      },
      {
        id: '6',
        title: 'Southern Artisan Craft Fair',
        time: '10:00 AM - 5:00 PM',
        location: 'Centennial Park, Nashville, TN',
        category: 'Marketplace',
        image: '/images/movie-park.jpg',
        description: 'Discover unique, handcrafted goods from local and regional artisans, including jewelry, pottery, textiles, and more.',
      },
      {
        id: '7',
        title: 'Nashville Hot Chicken Festival',
        time: '11:00 AM - 6:00 PM',
        location: 'East Park, Nashville, TN',
        category: 'Food & Drink',
        image: '/images/movie-park.jpg',
        description: 'A fiery food festival dedicated to Nashville\'s famous spicy dish, featuring food vendors, live music, and a hot chicken cooking competition.',
      },
      {
        id: '8',
        title: 'Tennessee State Fair',
        time: 'Various Times',
        location: 'Tennessee State Fairgrounds, Nashville, TN',
        category: 'Fair',
        image: '/images/movie-park.jpg',
        description: 'An annual tradition with agricultural exhibits, livestock shows, carnival rides, games, live entertainment, and delicious fair food.',
      },
      {
        id: '9',
        title: 'Nashville Oktoberfest',
        time: '10:00 AM - 10:00 PM',
        location: 'Germantown, Nashville, TN',
        category: 'Festival',
        image: '/images/movie-park.jpg',
        description: 'Celebrate German culture with traditional music, food, beer, and games in the historic Germantown neighborhood.',
      },
      {
        id: '10',
        title: 'Dia de los Muertos Celebration',
        time: '6:00 PM - 10:00 PM',
        location: 'Frist Art Museum, Nashville, TN',
        category: 'Culture',
        image: '/images/movie-park.jpg',
        description: 'A vibrant celebration of the Day of the Dead, honoring loved ones with traditional music, dance, art, and altars.',
      },
      {
        id: '11',
        title: 'Nashville Christmas Parade',
        time: '9:00 AM',
        date: 'December 25, 2023',
        location: 'Downtown Nashville, TN',
        category: 'Holiday',
        image: '/images/movie-park.jpg',
        description: 'A festive parade featuring marching bands, floats, local celebrities, and Santa Claus, spreading holiday cheer through downtown Nashville.',
      },
      {
        id: '12',
        title: 'New Year\'s Eve Live: The Music City Midnight',
        time: '7:00 PM - 1:00 AM',
        location: 'Downtown Nashville, TN',
        category: 'Music',
        image: '/images/movie-park.jpg',
        description: 'Ring in the New Year with live music performances, a midnight countdown, and the iconic Music Note Drop in the heart of Nashville.',
      },

      {
        id: '13',
        title: 'Nashville Boat Show',
        time: '10:00 AM - 8:00 PM',
        location: 'Music City Center, Nashville, TN',
        category: 'Hobbies',
        image: '/images/movie-park.jpg',
        description: 'Explore a wide selection of boats, yachts, personal watercraft, and marine accessories from top manufacturers and dealers.',
      },
      {
        id: '14',
        title: 'Nashville Home Show',
        time: '10:00 AM - 7:00 PM',
        location: 'Music City Center, Nashville, TN',
        category: 'Home Improvement',
        image: '/images/movie-park.jpg',
        description: 'Find inspiration and resources for home renovation, remodeling, and design projects, with exhibits from contractors, designers, and suppliers.',
      },
    {
        id: '15',
        title: 'SEC Men\'s Basketball Tournament',
        time: 'Various Game Times',
        location: 'Bridgestone Arena, Nashville, TN',
        category: 'Sports',
        image: '/images/movie-park.jpg',
        description: 'Cheer on your favorite Southeastern Conference basketball teams as they compete for the championship title.',
    },
    {
      id: '16',
      title: 'Nashville Cherry Blossom Festival',
      time: '9:30 AM - 5:00 PM',
      location: 'Public Square Park, Nashville, TN',
      category: 'Culture',
      image: '/images/movie-park.jpg',
      description: 'Celebrate the beauty of spring and Japanese culture with traditional music, dance, food, and the stunning display of cherry blossoms.',
    },
    {
      id: '17',
      title: 'Tennessee Craft Fair Spring Show',
      time: '10:00 AM - 6:00 PM',
      location: 'Centennial Park, Nashville, TN',
      category: 'Arts & Culture',
      image: '/images/movie-park.jpg',
      description: 'A juried craft fair showcasing the work of talented Tennessee artists and craftspeople, with unique handmade items for sale.',
    },
    {
      id: '18',
      title: 'Great Escape Game Show',
      time: 'All Day',
      location: 'Nashville Fairgrounds, Nashville, TN',
      category: 'Hobbies',
      image: '/images/movie-park.jpg',
      description: 'A weekend event for board game enthusiasts, featuring tournaments, open gaming, vendors, and opportunities to play your favorite games.',
    },
    {
      id: '19',
      title: 'Juneteenth Celebration',
      time: 'Various Events',
      location: 'Hadley Park, Nashville, TN',
      category: 'Community',
      image: '/images/movie-park.jpg',
      description: 'Commemorate the end of slavery in the United States with a day of reflection, celebration, and cultural activities.',
    },
    {
      id: '20',
      title: 'Nashville Comic Con',
      time: '10:00 AM - 6:00 PM',
      location: 'Music City Center, Nashville, TN',
      category: 'Hobbies',
      image: '/images/movie-park.jpg',
      description: 'A pop culture convention featuring celebrity guests, comic book artists, vendors, panels, and cosplay contests.',
    },
    {
      id: '21',
      title: 'Cheekwood in Bloom',
      time: '9:00 AM - 5:00 PM',
      location: 'Cheekwood Estate & Gardens, Nashville, TN',
      category: 'Nature',
      image: '/images/movie-park.jpg',
      description: 'Experience the beauty of spring with a stunning display of colorful flowers, blooming trees, and vibrant gardens at Cheekwood.',
    },
    {
      id: '22',
      title: 'Nashville Whiskey Festival',
      time: '6:00 PM - 9:00 PM',
      location: 'Omni Hotel, Nashville, TN',
      category: 'Food & Drink',
      image: '/images/movie-park.jpg',
      description: 'A premium tasting event featuring a wide selection of whiskeys from local distilleries and around the world.',
    },
    {
      id: '23',
      title: 'Live on the Green Music Festival',
      time: 'Various Times',
      location: 'Public Square Park, Nashville, TN',
      category: 'Music',
      image: '/images/movie-park.jpg',
      description: 'A free outdoor music festival showcasing a diverse lineup of local and national artists across various genres.',
    },
    {
      id: '24',
      title: 'Nashville Predators Hockey Season',
      time: 'Various Game Times',
      location: 'Bridgestone Arena, Nashville, TN',
      category: 'Sports',
      image: '/images/movie-park.jpg',
      description: 'Cheer on the Nashville Predators as they compete in the National Hockey League (NHL) season.',
    },
      {
        id: '25',
        title: 'Nashville Farmers Market',
        time: '8:00 AM - 6:00 PM',
        location: 'Nashville Farmers\' Market, Nashville, TN',
        category: 'Marketplace',
        image: '/images/movie-park.jpg',
        description: 'A vibrant market offering fresh, locally grown produce, artisanal goods, food vendors, and a variety of cultural events.',
      },
      {
        id: '26',
        title: 'Nashville Zoo at Night',
        time: '6:00 PM - 10:00 PM',
        location: 'Nashville Zoo, Nashville, TN',
        category: 'Family',
        image: '/images/movie-park.jpg',
        description: 'Experience the Nashville Zoo in a whole new light with extended hours, special exhibits, and family-friendly activities after dark.',
      },
      {
        id: '27',
        title: 'Artober Nashville',
        time: 'Various Events',
        location: 'Various Locations, Nashville, TN',
        category: 'Arts & Culture',
        image: '/images/movie-park.jpg',
        description: 'A month-long celebration of Nashville\'s vibrant arts scene, featuring exhibitions, performances, workshops, and cultural events throughout the city.',
      },
      {
        id: '28',
        title: 'Nashville Running Festival',
        time: 'Various Race Times',
        location: 'Shelby Bottoms Park, Nashville, TN',
        category: 'Sports',
        image: '/images/movie-park.jpg',
        description: 'A weekend of races for runners of all levels, including a marathon, half marathon, 10K, and 5K, showcasing Nashville\'s scenic beauty.',
      },
        {
          id: '29',
          title: 'Nashville International Airport (BNA) 35th Anniversary Celebration',
          time: '10:00 AM - 4:00 PM',
          location: 'Nashville International Airport (BNA), Nashville, TN',
          category: 'Community',
          image: '/images/movie-park.jpg',
          description: 'Celebrate the 35th anniversary of Nashville International Airport with special events, exhibits, and activities for the community.',
        },
        {
            id: '30',
            title: 'Nashville Pride Month',
            time: 'All Month',
            location: 'Various Locations, Nashville, TN',
            category: 'Community',
            image: '/images/movie-park.jpg',
            description: 'A month-long series of events celebrating the LGBTQ+ community in Nashville, promoting diversity, inclusion, and equality.',
        },
        {
          id: '31',
          title: 'Nashville Predators Foundation Fundraiser',
          time: '6:00 PM - 10:00 PM',
          location: 'The Country Music Hall of Fame and Museum, Nashville, TN',
          category: 'Charity',
          image: '/images/movie-park.jpg',
          description: 'A fundraising event to support the Nashville Predators Foundation, featuring a silent auction, dinner, and special guests.',
        },
        {
            id: '32',
            title: 'Nashville Public Library Book Sale',
            time: '9:00 AM - 5:00 PM',
            location: 'Nashville Public Library, Main Branch, Nashville, TN',
            category: 'Literary',
            image: '/images/movie-park.jpg',
            description: 'A sale of used books, CDs, and DVDs to benefit the Nashville Public Library, offering a wide selection at affordable prices.',
        },
    ];
  }
